server.port=8081
server.servlet.context-path=/ProtVar

spring.ai.mcp.server.name=protvar-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STATELESS
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/mcp/actuator

protvar.api.base-url=https://wwwdev.ebi.ac.uk/ProtVar/api